### ISSUE TITLE
generate_arn for IAM adds region

### ISSUE THREAD

**Issue by lllama** [tableau/altimeter#124]
IAM role resources appear to have the region added to their ARN which isn't required (https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html#identifiers-arns). This in turn breaks links when trying to add connections to them (an example is the `RoleArn` attribute of lambda functions.)

**Comment by jbmchuck** [comment]
Thanks for the report @lllama , this should be fixed in master and in the latest release, 6.0.5. I went ahead and added the Lambda Func -> IAM Role link as a validation.

**Comment by lllama** [comment]
Awesome! I hacked in a fix locally and it more of less matched your pull request which I think shows how nice this code is to work with - very well organised and easy to understand.

I have a couple of feature suggestions that I will add elsewhere as issues.

**Comment by jbmchuck** [comment]
Please do, we're very open to suggestions.
