### ISSUE TITLE
Cut a new release including the merged PRs #168 and #163

### ISSUE THREAD

**Issue by jroimartin** [tableau/altimeter#170]
@jbmchuck, if I'm not wrong, after merging the PRs #168 and #163 no releases have been cut. Would it make sense to cut a new release including them?

```
$ git log --oneline 6.4.4..master
525750f (HEAD -> master, upstream/master, upstream/HEAD, origin/master) Gather user and group policies (#163)
09f974a Make the field UserId in a Security Group optional (#168)
```

Thanks in advance!

**Comment by jbmchuck** [comment]
Thanks! Created release https://github.com/tableau/altimeter/releases/tag/6.4.5 and published pypi and docker artifacts.

**Comment by jroimartin** [comment]
@jbmchuck thanks! However, pip cannot find the new package in PyPI:

```
ERROR: Could not find a version that satisfies the requirement altimeter==6.4.5
```

Also, the [PyPI website shows 6.4.4 as the latest version](https://pypi.org/project/altimeter/). Maybe an error? The docker images seem to be updated.

**Comment by jbmchuck** [comment]
Thanks - indeed the build/push pipeline broke - this is fixed now: https://pypi.org/project/altimeter/6.4.5/
