### ISSUE TITLE
 NoRegionError: You must specify a region. causing Altimeter to crash on use.

### ISSUE THREAD

**Issue by dmoore247** [tableau/altimeter#179]
This [line](https://github.com/tableau/altimeter/blob/fdb69b44833ba6f6be4b19cf0b14b3265863fffd/altimeter/core/config.py#L94) of code causes Altimeter to crash upon first use.
`s3_client = boto3.client("s3")` throws ` NoRegionError: You must specify a region.` error because the region parameter is not specified and the `AWS_DEFAULT_REGION` environment variable wasn't specified.

Suggest either adding region parameter to the call based on what's in the config file or pick a region by default, or tell user to set `AWS_DEFAULT_REGION` and/or update documentation.

**Comment by jbmchuck** [comment]
Thanks for the report - the entrypoint bash script has been updated to detect this as of 6.4.18 - https://github.com/tableau/altimeter/pull/207/files#diff-e5f16e411360ad8e6f528dea8207537a71c2dca1869926d152c00017bde3ff4d
