### ISSUE TITLE
quick start example runs into errors

### ISSUE THREAD

**Issue by ameydhavle** [tableau/altimeter#52]
Using the quickstart guide and running the below command runs to error. Am I missing some confirguration. I have AWS CLI setup and all the aws cli commands work fine.
 altimeter --base_dir /tmp/altimeter --regions us-east-1
usage: aws2json.py [-h] --config CONFIG output_dir
aws2json.py: error: the following arguments are required: --config

**Comment by jbmchuck** [comment]
Thanks for the report! Documentation has been updated with the current usage - most options are now driven by a configuration file.  A sample config file `conf/current_single_account.toml` is probably what you'll want to try - this will scan the currently configured account:

    altimeter --config conf/current_single_account.toml /tmp/altimeter
