### ISSUE TITLE
./altimeter: line 9: aws2n.py: command not found

### ISSUE THREAD

**Issue by gvasquez95** [tableau/altimeter#74]
Seems like `pip` didn't leave everything ok, or perhaps I'm missing some instructions on how to run it.

altimeter was installed at: `/Users/gonzalovasquez/Library/Python/3.7/bin/altimeter` as my user  and also with `sudo` at `/System/Volumes/Data/Users/gonzalovasquez/Library/Python/3.7/bin/altimeter`, but both yield same error message about the missing aws2n.py 

Facts:
```
aws --version
aws-cli/2.0.15 Python/3.7.4 Darwin/19.6.0 botocore/2.0.0dev19
```

macOS Catalina 10.15.7

**Comment by jbmchuck** [comment]
Could your provide the output of:

which altimeter
ls $(dirname $(which altimeter))
echo $PATH

?

Thanks,
Jon

**Comment by gvasquez95** [comment]
`which` yields no results, so the second line doesn't either.

PATH is as follows and shows references to Python 2.7:

`/Users/gonzalovasquez/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Users/gonzalovasquez/Library/Python/2.7/bin:~/Library/Python/2.7/bin`

**Comment by jbmchuck** [comment]
Hi @gvasquez95 ,

It looks likely to be a PATH issue.  You'll want to add the path of aws2n.py to your PATH.  I'd first suggest upgrading to latest, which you should be able to do without sudo:

    pip3 install altimeter==2.0.5

Depending on your system I'm guessing aws2n.py will be somewhere like one of the paths below.  I'm assuming you are on 3.8:

    /Library/Frameworks/Python.framework/Versions/3.8/bin
    /Users/gonzalovasquez/Library/Python/3.8/bin

Assuming aws2n.py is in `/Users/gonzalovasquez/Library/Python/3.8/bin` you can then run:

    export PATH="$PATH:$HOME/Library/Python/3.8/bin"

and running 'altimeter' should find aws2n.py

To make this permanent you'll want to edit your shell's rc file - zsh / ~/.zshrc, and update PATH to something like:

    PATH=$PATH:$HOME/Library/Python/3.8/bin

**Comment by jbmchuck** [comment]
Closing due to age. Please feel free to open a new issue if this is still an issue after the latest comment.
